version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Install packages
          command: npm install
          
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install
          command: node express.js
      
        
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build          
