version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout

      - run:
          name: Install packages
          command: npm install
      - run:
          name: ifconfig
          command: ifconfig

  deploy:
    docker:
      - image: circleci/node:16

    working_directory: ~/my-express-app

    steps:
      - checkout
      - run:
          name: ssh connect
          command: ssh ubuntu@ec2-54-204-74-104.compute-1.amazonaws.com
          
        
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build          
