version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      - run:
          name: Install packages
          command: npm install

      - run:
          name: Run tests
          command: npm test
          
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build and deploy
          command: npm run build && npm run deploy

         
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build          
