version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14
    steps:
      - checkout

      - run:
          name: Install packages
          command: npm install

      - run:
          name: Run tests
          command: npm test
